### ISSUE TITLE
 Connected to broker at KAFKA_SERVER:9092 (unregistered)

### ISSUE THREAD

**Issue by psicatrie** [danielqsj/kafka_exporter#114]
Hello Everyone,
I hope you're doing well and better than me :).

I downloaded the last version of kafka exporter then just tar the gz, but the exporter doesn't starts. any ideas ? "i also tried the ip adress but still same problem"

I thought i may have to use the TLS options, but the only file i have are:
keystore.jks
truststore.jks

I tried using --tls.key-file="trustore.jks" but still doesn't work. i guess it's not the right way.

Thanks in advance.
Have a good day

LOGS:
/usr/bin/kafka_exporter --kafka.server=SERVER_KAFKA1:9092 --log.enable-sarama              INFO[0000] Starting kafka_exporter (version=1.2.0, branch=HEAD, revision=830660212e6c109e69dcb1cb58f5159fe3b38903)  source="kafka_exporter.go:474"
INFO[0000] Build context (go=go1.10.3, user=root@981cde178ac4, date=20180707-14:34:48)  source="kafka_exporter.go:475"
[sarama] 2019/07/23 17:21:58 Initializing new client
[sarama] 2019/07/23 17:21:58 client/metadata fetching metadata for all topics from broker s2994aos.mc2.renault.fr:9092
[sarama] 2019/07/23 17:21:58 Connected to broker at SERVER_KAFKA1:9092 (unregistered)
[sarama] 2019/07/23 17:21:58 client/metadata got error from broker while fetching metadata: unexpected EOF
[sarama] 2019/07/23 17:21:58 Closed connection to broker SERVER_KAFKA1:9092
[sarama] 2019/07/23 17:21:58 client/metadata no available broker to send metadata request to
[sarama] 2019/07/23 17:21:58 client/brokers resurrecting 1 dead seed brokers
[sarama] 2019/07/23 17:21:58 client/metadata retrying after 250ms... (3 attempts remaining)
[sarama] 2019/07/23 17:21:59 client/metadata fetching metadata for all topics from broker s2994aos.mc2.renault.fr:9092
[sarama] 2019/07/23 17:21:59 Connected to broker at SERVER_KAFKA1:9092 (unregistered)
[sarama] 2019/07/23 17:21:59 client/metadata got error from broker while fetching metadata: unexpected EOF
[sarama] 2019/07/23 17:21:59 Closed connection to broker SERVER_KAFKA1:9092
[sarama] 2019/07/23 17:21:59 client/metadata no available broker to send metadata request to
[sarama] 2019/07/23 17:21:59 client/brokers resurrecting 1 dead seed brokers

[sarama] 2019/07/23 17:21:59 client/metadata got error from broker while fetching metadata: unexpected EOF
[sarama] 2019/07/23 17:21:59 Closed connection to broker SERVER_KAFKA1:9092
[sarama] 2019/07/23 17:21:59 client/metadata no available broker to send metadata request to
[sarama] 2019/07/23 17:21:59 client/brokers resurrecting 1 dead seed brokers
[sarama] 2019/07/23 17:21:59 Closing Client
ERRO[0000] Error Init Kafka Client                       source="kafka_exporter.go:210"
panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

goroutine 1 [running]:
main.NewExporter(0xc420204240, 0x1, 0x1, 0x100, 0x8f22f8, 0x0, 0x8f22f8, 0x0, 0x0, 0x8f22f8, ...)
        /go/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:211 +0x847
main.main()
        /go/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:481 +0x215b

**Comment by sebco59** [comment]
Did you try with `--tls.insecure-skip-tls-verify`

View my reply here: https://github.com/danielqsj/kafka_exporter/issues/116#issuecomment-559108062
