### ISSUE TITLE
Kafka exporter not working with SASL/SCRAM 

### ISSUE THREAD

**Issue by tonyjune** [danielqsj/kafka_exporter#120]
Our kafka cluster has SASL/SCRAM security mechanism and kafka exporter throws this error-

```
INFO[0000] Starting kafka_exporter (version=1.2.0, branch=HEAD, revision=830660212e6c109e69dcb1cb58f5159fe3b38903)  source="kafka_exporter.go:474"
INFO[0000] Build context (go=go1.10.3, user=root@981cde178ac4, date=20180707-14:34:48)  source="kafka_exporter.go:475"
ERRO[0001] Error Init Kafka Client                       source="kafka_exporter.go:210"
panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

goroutine 1 [running]:
main.NewExporter(0xc42006a420, 0x1, 0x1, 0x100, 0x7ffd8252476a, 0xb, 0x7ffd82524786, 0x12, 0x1, 0x7ffd825247a7, ...)
        /go/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:211 +0x847
main.main()
        /go/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:481 +0x215b
```

PS- It works fine with SASL/PLAIN. 
Is it known issue?

**Comment by tmendenhall** [comment]
Can you please post your configuration parameters for SASL/PLAIN? I am attempting to connect to a ConfluentCloud hosted Kafka cluster authenticated with sasl.mechanism=PLAIN and security.protocol=SASL_SSL

**Comment by sebco59** [comment]
> Can you please post your configuration parameters for SASL/PLAIN? I am attempting to connect to a ConfluentCloud hosted Kafka cluster authenticated with sasl.mechanism=PLAIN and security.protocol=SASL_SSL

Me too and it works now with `--tls.insecure-skip-tls-verify` and `--tls.enabled`

View my reply here: https://github.com/danielqsj/kafka_exporter/issues/116#issuecomment-559108062

**Comment by knil-sama** [comment]
Only needed to add --tls.insecure-skip-tls-verify in my case, thanks for your reply :+1:

**Comment by leonrado** [comment]
I have the same "issue", But add --tls.insecure-skip-tls-verify does not working for me. I'm no using TLS
Parameters for SASL:
```
bootstrap.servers=localhost:9092
security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-256
```
./kafka_exporter --sasl.enabled --sasl.username="xxx" --sasl.password="xxx"  --tls.enabled --tls.insecure-skip-tls-verify  --kafka.version=2.12.2 --log.level=debug

```
INFO[0000] Starting kafka_exporter (version=1.2.0, branch=HEAD, revision=830660212e6c109e69dcb1cb58f5159fe3b38903)  source="kafka_exporter.go:474"
INFO[0000] Build context (go=go1.10.3, user=root@981cde178ac4, date=20180707-14:34:48)  source="kafka_exporter.go:475"
ERRO[0000] Error Init Kafka Client                       source="kafka_exporter.go:210"
panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

goroutine 1 [running]:
main.NewExporter(0xc4200817c0, 0x1, 0x1, 0x101, 0x7ffd57bb8606, 0x5, 0x7ffd57bb861c, 0xd, 0x1, 0x8f22f8, ...)
	/go/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:211 +0x847
main.main()
	/go/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:481 +0x215b
```

**Comment by Yuanyp8** [comment]
I met the same mistake, is there any solution

**Comment by wangmingch** [comment]
I met the same mistake, is there any solution

**Comment by srirajk** [comment]
I am also running into the same issue.

**Comment by srirajk** [comment]
it looks like the latest docker image does not have the changes for scram support. Its not built from master branch

**Comment by sandjaie** [comment]
what worked for me is 

```
./kafka_exporter  --kafka.server=url:port \
  --web.listen-address=:7071 \
  --sasl.enabled \
  --sasl.username="user" \
  --sasl.password="password" \
  --sasl.kerberos-auth-type="userAuth" \
  --sasl.mechanism="scram-sha512" \
  --tls.insecure-skip-tls-verify \
  --tls.enabled \
  --log.level=debug
  ```

**Comment by reilee** [comment]
Thanks @sandjaie for the solution, I was missing `--sasl.enabled`

**Comment by Valeriyy** [comment]
It's not working
```
# /bin/kafka_exporter --kafka.server=10.5.107.12:9092 --sasl.enabled --sasl.username="kafka-internal" --sasl.password="mypass" --sasl.mechanism="scram-sha256" --tls.insecure-skip-tls-verify --tls.enabled --log.enable-sarama 
I0205 22:37:03.284519 2584746 kafka_exporter.go:850] Starting kafka_exporter (version=1.9.0, branch=HEAD, revision=8ec24078707d4d3b349e71522ebd7f179746072d)
[sarama] 2026/02/05 22:37:03 Initializing new client
[sarama] 2026/02/05 22:37:03 client/metadata fetching metadata for all topics from broker 10.5.107.12:9092
[sarama] 2026/02/05 22:37:03 Error while performing SASL handshake 10.5.107.12:9092: remote error: tls: handshake failure
[sarama] 2026/02/05 22:37:03 Closed connection to broker 10.5.107.12:9092 due to SASL v1 auth error: remote error: tls: handshake failure
[sarama] 2026/02/05 22:37:03 client/metadata got error from broker -1 while fetching metadata: remote error: tls: handshake failure
[sarama] 2026/02/05 22:37:03 client/metadata no available broker to send metadata request to
[sarama] 2026/02/05 22:37:03 client/brokers resurrecting 1 dead seed brokers
[sarama] 2026/02/05 22:37:03 client/metadata retrying after 250ms... (2 attempts remaining)
[sarama] 2026/02/05 22:37:03 client/metadata fetching metadata for all topics from broker 10.5.107.12:9092
[sarama] 2026/02/05 22:37:03 Error while performing SASL handshake 10.5.107.12:9092: remote error: tls: handshake failure
[sarama] 2026/02/05 22:37:03 Closed connection to broker 10.5.107.12:9092 due to SASL v1 auth error: remote error: tls: handshake failure
[sarama] 2026/02/05 22:37:03 client/metadata got error from broker -1 while fetching metadata: remote error: tls: handshake failure
[sarama] 2026/02/05 22:37:03 client/metadata no available broker to send metadata request to
[sarama] 2026/02/05 22:37:03 client/brokers resurrecting 1 dead seed brokers
[sarama] 2026/02/05 22:37:03 client/metadata retrying after 250ms... (1 attempts remaining)
[sarama] 2026/02/05 22:37:03 client/metadata fetching metadata for all topics from broker 10.5.107.12:9092
[sarama] 2026/02/05 22:37:03 Error while performing SASL handshake 10.5.107.12:9092: remote error: tls: handshake failure
[sarama] 2026/02/05 22:37:03 Closed connection to broker 10.5.107.12:9092 due to SASL v1 auth error: remote error: tls: handshake failure
[sarama] 2026/02/05 22:37:03 client/metadata got error from broker -1 while fetching metadata: remote error: tls: handshake failure
[sarama] 2026/02/05 22:37:03 client/metadata no available broker to send metadata request to
[sarama] 2026/02/05 22:37:03 client/brokers resurrecting 1 dead seed brokers
[sarama] 2026/02/05 22:37:04 client/metadata retrying after 250ms... (0 attempts remaining)
[sarama] 2026/02/05 22:37:04 client/metadata fetching metadata for all topics from broker 10.5.107.12:9092
[sarama] 2026/02/05 22:37:04 Error while performing SASL handshake 10.5.107.12:9092: remote error: tls: handshake failure
[sarama] 2026/02/05 22:37:04 Closed connection to broker 10.5.107.12:9092 due to SASL v1 auth error: remote error: tls: handshake failure
[sarama] 2026/02/05 22:37:04 client/metadata got error from broker -1 while fetching metadata: remote error: tls: handshake failure
[sarama] 2026/02/05 22:37:04 client/metadata no available broker to send metadata request to
[sarama] 2026/02/05 22:37:04 client/brokers resurrecting 1 dead seed brokers
[sarama] 2026/02/05 22:37:04 Closing Client
F0205 22:37:04.044213 2584746 kafka_exporter.go:951] Error Init Kafka Client: kafka: client has run out of available brokers to talk to: remote error: tls: handshake failure
```

It appears kafka_exporter (via sarama library) is attempting SASL handshake before TLS handshake is complete. The log shows Error while performing SASL handshake...: remote error: tls: handshake failure - meaning SASL is attempted, THEN TLS fails.
The sarama library may need to ensure TLS handshake completes BEFORE attempting any SASL authentication when security.protocol=SASL_SSL. Other Kafka clients handle this correctly.
Workarounds that DON'T work:
    Using --no-sasl.handshake doesn't help
