### ISSUE TITLE
"Index out of range" error when cluster is rebalancing

### ISSUE THREAD

**Issue by ekarak** [danielqsj/kafka_exporter#14]
```time="2018-02-12T06:32:49+01:00" level=error msg="Can't get oldest offset of topic events partition %!s(int32=2): kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes." source="kafka_exporter.go:176"
panic: runtime error: index out of range

goroutine 729480 [running]:
main.(*Exporter).Collect(0xc4200df0a0, 0xc42eeb6a80)
	/go/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:201 +0x2d15
github.com/danielqsj/kafka_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc42ef98230, 0xc42eeb6a80, 0xb3ce60, 0xc4200df0a0)
	/go/src/github.com/danielqsj/kafka_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:433 +0x61
created by github.com/danielqsj/kafka_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/src/github.com/danielqsj/kafka_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:431 +0x2e1
```

kafka_exporter, version 0.2.0 (branch: HEAD, revision: 9aecc7d5965edf2230f8eb6992103396dfc11041)

**Comment by ekarak** [comment]
https://github.com/danielqsj/kafka_exporter/blob/9aecc7d5965edf2230f8eb6992103396dfc11041/kafka_exporter.go#L201

```
					if broker != nil && replicas != nil && broker.ID() == replicas[0] {
```

_probably_ replicas is not nil, but an empty array

**Comment by danielqsj** [comment]
@ekarak Thanks a lot.
