### ISSUE TITLE
connect kafka

### ISSUE THREAD

**Issue by osenlin** [danielqsj/kafka_exporter#38]
➜  kafka docker run -ti --rm -p 9308:9308 danielqsj/kafka-exporter --kafka.server=localhost:9092 --kafka.server=localhost:9093 --kafka.server=localhost:9094
INFO[0000] Starting kafka_exporter (version=1.1.0, branch=HEAD, revision=b87796c32ab4376fe6d47fb17df6a41cca21b046)  source="kafka_exporter.go:463"
INFO[0000] Build context (go=go1.9, user=travis@travis-job-a0256c7c-80b7-43b1-8756-c973a09fc3c9, date=20180521-08:56:09)  source="kafka_exporter.go:464"
ERRO[0000] Error Init Kafka Client                       source="kafka_exporter.go:209"
panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

goroutine 1 [running]:
main.NewExporter(0xc420144440, 0x3, 0x4, 0x100, 0x8ffc58, 0x0, 0x8ffc58, 0x0, 0x0, 0x8ffc58, ...)
	/home/travis/gopath/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:210 +0x94a
main.main()
	/home/travis/gopath/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:470 +0x1f95

**Comment by danielqsj** [comment]
@osenlin Kafka_exporter can not reach this kafka cluster. Please check whether this kafka cluster is reachable.
