### ISSUE TITLE
unexpected EOF

### ISSUE THREAD

**Issue by dheerajkulakarni** [danielqsj/kafka_exporter#83]
``Starting kafka_exporter (version=1.2.0, branch=HEAD, revision=5fb725fd1933a83d654194ffc8cf22254ec0f3a9)  source="kafka_exporter.go:475"
INFO[0000] Build context (go=go1.9, user=travis@travis-job-418981c5-7f03-48cb-b74a-e7640fb024e3, date=20181112-12:40:58)  source="kafka_exporter.go:476"
[sarama] 2018/11/20 09:43:28 Initializing new client
[sarama] 2018/11/20 09:43:28 client/metadata fetching metadata for all topics from broker xyz:9092
[sarama] 2018/11/20 09:43:29 SASL authentication successful with broker xyz:9092:4 - [21 3 3 0]
[sarama] 2018/11/20 09:43:29 Connected to broker at xyz:9092 (unregistered)
[sarama] 2018/11/20 09:43:29 client/metadata got error from broker while fetching metadata: unexpected EOF
[sarama] 2018/11/20 09:43:29 Closed connection to broker xyz:9092
[sarama] 2018/11/20 09:43:29 client/metadata no available broker to send metadata request to
[sarama] 2018/11/20 09:43:29 client/brokers resurrecting 1 dead seed brokers
[sarama] 2018/11/20 09:43:29 client/metadata retrying after 250ms... (3 attempts remaining)
[sarama] 2018/11/20 09:43:30 client/metadata fetching metadata for all topics from broker xyz:9092
[sarama] 2018/11/20 09:43:30 SASL authentication successful with broker xyz:9092:4 - [21 3 3 0]
[sarama] 2018/11/20 09:43:30 Connected to broker at xyz:9092 (unregistered)
[sarama] 2018/11/20 09:43:30 client/metadata got error from broker while fetching metadata: unexpected EOF
[sarama] 2018/11/20 09:43:30 Closed connection to broker xyz:9092
[sarama] 2018/11/20 09:43:30 client/metadata no available broker to send metadata request to
[sarama] 2018/11/20 09:43:30 client/brokers resurrecting 1 dead seed brokers
[sarama] 2018/11/20 09:43:30 client/metadata retrying after 250ms... (2 attempts remaining)
[sarama] 2018/11/20 09:43:31 client/metadata fetching metadata for all topics from broker xyz:9092
[sarama] 2018/11/20 09:43:31 SASL authentication successful with broker xyz:9092:4 - [21 3 3 0]
[sarama] 2018/11/20 09:43:31 Connected to broker at xyz:9092 (unregistered)
[sarama] 2018/11/20 09:43:31 client/metadata got error from broker while fetching metadata: unexpected EOF
[sarama] 2018/11/20 09:43:31 Closed connection to broker xyz:9092
[sarama] 2018/11/20 09:43:31 client/metadata no available broker to send metadata request to
[sarama] 2018/11/20 09:43:31 client/brokers resurrecting 1 dead seed brokers
[sarama] 2018/11/20 09:43:31 client/metadata retrying after 250ms... (1 attempts remaining)
[sarama] 2018/11/20 09:43:32 client/metadata fetching metadata for all topics from broker xyz:9092
[sarama] 2018/11/20 09:43:32 SASL authentication successful with broker xyz:9092:4 - [21 3 3 0]
[sarama] 2018/11/20 09:43:32 Connected to broker at xyz:9092
[sarama] 2018/11/20 09:43:32 client/metadata got error from broker while fetching metadata: unexpected EOF
[sarama] 2018/11/20 09:43:32 Closed connection to broker 

> `xyz:9092`

[sarama] 2018/11/20 09:43:32 client/metadata no available broker to send metadata request to
[sarama] 2018/11/20 09:43:32 client/brokers resurrecting 1 dead seed brokers
[sarama] 2018/11/20 09:43:32 Closing Client
ERRO[0003] Error Init Kafka Client                       source="kafka_exporter.go:171"
panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

goroutine 1 [running]:
main.NewExporter(0xc42006bdd0, 0x1, 0x1, 0x1, 0x7fff67540f00, 0x10, 0x7fff67540f21, 0x40, 0x0, 0x933c18, ...)
	/home/travis/gopath/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:172 +0xa69
main.main()
	/home/travis/gopath/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:581 +0x38bc`

 `

> I am getting unexpected eof while fetching metadata after SASL successful authentication ,above attached are the detailed logs . can you please help with this

**Comment by dheerajkulakarni** [comment]
Any updates on this?

**Comment by batmac** [comment]
same problem here.

**Comment by sebco59** [comment]
Did you try with `tls.enabled` and `tls.insecure-skip-tls-verify` ?

View my reply here : https://github.com/danielqsj/kafka_exporter/issues/116#issuecomment-559108062
