### ISSUE TITLE
panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

### ISSUE THREAD

**Issue by pradipdevops** [danielqsj/kafka_exporter#98]
not able to run kafka_exporter with below details :

kafka sasl details in server.properties file:

listener.security.protocol.map=SASL_PLAINTEXT:SASL_PLAINTEXT
sasl.enabled.mechanisms=SCRAM-SHA-256
security.inter.broker.protocol=SASL_PLAINTEXT
sasl.mechanism.inter.broker.protocol=SCRAM-SHA-256
authorizer.class.name=kafka.security.auth.SimpleAclAuthorizer

Comamnd:

nohup ./kafka_exporter --kafka.version="2.2.0"   --no-sasl.handshake --sasl.enabled  --sasl.username="xyz" --sasl.password="abc" --kafka.server=10.0.0.1:9091 --kafka.server=10.0.0.2:9092 --kafka.server=10.0.0.3:9093 --log.level="debug" --log.enable-sarama --log.format="logger:syslog?appname=bob&local=7"  &

Error:

panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

goroutine 1 [running]:
main.NewExporter(0xc4201d2140, 0x3, 0x4, 0x1, 0x7ffe159a844c, 0x5, 0x7ffe159a8462, 0xe, 0x0, 0x8f22f8, ...)
        /go/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:211 +0x847
main.main()
        /go/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:481 +0x215b

**Comment by squ1d123** [comment]
This is due to kafka-exporter not supporting SCRAM as a sasl mechanism. At the moment it only supports PLAN as a SASL mechanism. This is due to go library that kafka-exporter uses (samara) didn't support it. However the good news it that samara it now supports it <https://github.com/Shopify/sarama/pull/1295>.

**Comment by pradipdevops** [comment]
Hi squ1d123,
Thanks, as you know go library samara now supports SCARM as a sasl mechanism, can we know when Kafka exporter support SCRAM as a sasl mechanism? estimate next prod release date?

**Comment by squ1d123** [comment]
I have just opened <https://github.com/danielqsj/kafka_exporter/pull/101> to support this, feel free to use my branch in the meantime if you want to try it out

**Comment by codebyte** [comment]
KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://<YOUR IP>:9092'

Add this under kakfa docker

**Comment by jayson-wang** [comment]
I had the same problem
i want to use SCRAM-SHA-256
but  report this error
The latest version is still 1.2 now

**Comment by hugo-oliveira-jumia** [comment]
im facing the same issue. 
I use the following configurations

```
sasl.enabled.mechanisms=SCRAM-SHA-256,SCRAM-SHA-512
sasl.mechanism.inter.broker.protocol=SCRAM-SHA-512
security.inter.broker.protocol=SASL_PLAINTEXT
```

Is there any further development in this topic?

**Comment by theliuk** [comment]
I'm facing the same issue with a Kafka instance running on Confluent.
I provided the following configuration:
```
--kafka.server="<kafka cluster>" --sasl.enabled --tls.enabled --sasl.username="<username>" --sasl.password="<password>"
```
I usually use SASL PLAIN mechanism to access my Kafka instance for other purposes.

I get

```
ERRO[0001] Error Init Kafka Client                       source="kafka_exporter.go:184"
panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

goroutine 1 [running]:
main.NewExporter(0xc420130280, 0x1, 0x1, 0x101, 0x7ffc35e1ff14, 0x10, 0x7ffc35e1ff35, 0x40, 0x1, 0x96d438, ...)
	/home/travis/gopath/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:185 +0xbbc
main.main()
	/home/travis/gopath/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:606 +0x3aa7
```
